### PR TITLE
SDR-2398 | Adds Models and /meta vendor endpoint 

### PR DESCRIPTION
**Pull request by ChinnaBabuSadam**

### CODE REVIEW

**Comment by RickyAmparoCloud** [comment]
The following resource is missing a Response and Request Model /employees/{employeeId}/personal-address.
Aside from that the security looks good and it was able to load successfully.

**Comment by ChinnaBabuSadam** [comment]
@RickyAmparoCloud 
Yes that's true
Since I couldn't find the vendor API for that.
Can you share the link to that, so that I can add it quickly

**Comment by RickyAmparoCloud** [comment]
@ChinnaBabuSadam I wasn't actually able to find the API docs for the personal address.add operation but rather only found the docs for the .change operation. This is a weird one, not sure if it's better to add the model for the legal address of leave it without a model. 

Here's the API documentation: https://developers.adp.com/articles/api/workers---personal-communication-management-v2-api

**Comment by ChinnaBabuSadam** [comment]
@RickyAmparoCloud 
exactly that's what I confused with
So, I just left it alone and forwarded to @kellytgold the same

**Pull request merged**
