### PR TITLE
NewsAPI Element

### PR DESCRIPTION
**Pull request by George-Novac**
Creating a pull request to add the NewsApi Element JSON and ReadMe.

### CODE REVIEW

**Comment by Jayme-T** [comment]
@nick-bair 

This was discussed via email 1) on the /everything endpoint it was weird that pagesize was required. Typically that is not a required parameter so I changed it to not be required and found it worked so I would make that optional
2) It is unclear how to use the q in the where filter on /everything endpoint as well. Should it look like where='q="something" ' ? I was having trouble trying to query a publishedAt date.
3) In the future consider making a CE usable sandbox and putting it in one pass for testing purposes but I went ahead and made a free trial to get an api key so it was not a blocker just an extra hurdle 


These changes were made and it should be good to merge I would do one last check to make sure that the files are named to work with the import functionality

**Comment by George-Novac** [comment]
Hi @nick-bair , I've added a commit with the requested changes, please advise if there is any other action required from me. Thank you!

**Comment by nick-bair** [comment]
Hi @George-Novac, awesome thanks!  One last ask, can you delete `.DS_Store` from your PR?  You may need to delete it, then add a `.gitignore` with the following:
```
.DS_Store
.gitignore
```

Let me know if that doesn't make sense or if you need some help.

Thanks

**Comment by nick-bair** [comment]
Hey @George-Novac closing out this PR so that you can re-initiate it from the CE UI (this will be the standard process going forward).  @kiawnna can you share instructions with George directly as he is not in the UTS channel?  Thanks

**Pull request closed without merging**
